databases:
  - name: what-to-cook-database
    databaseName: whattocookdatabase
    user: whattocookdatabaseuser
    plan: free

services:
  - type: web
    name: what-to-cook
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: what-to-cook-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync:false- key: WEB_CONCURRENCY
        value: 2
